"""Fixed, authored question contracts. Reference SQL is never shown to the agent.

Every question specifies its projection and ordering; all list results fit the
50-row application cap. Dev questions may guide fixes. Evaluation questions
must not guide prompt/code changes after the frozen run begins.
"""

def case(identifier, question, sql, tables, category, ordered=False):
    return dict(id=identifier, split='dev' if identifier.startswith('D') else 'eval',
                question=question, reference_sql=sql, required_tables=tables.split(),
                category=category, ordered=ordered)

CASES = [
case('D01','How many races were held in 2023? Return only the count.',
 'SELECT COUNT(*) AS n FROM races WHERE year=2023','races','count'),
case('D02','Return the surnames and career race-win counts of the top five drivers, ordered by wins descending then surname ascending.',
 "SELECT d.surname,COUNT(*) n FROM results r JOIN drivers d USING(driverId) WHERE r.position='1' GROUP BY d.driverId,d.surname ORDER BY n DESC,d.surname LIMIT 5",'results drivers','aggregation',True),
case('D03','List circuit names in Italy, sorted alphabetically.',
 "SELECT name FROM circuits WHERE country='Italy' ORDER BY name",'circuits','filter',True),
case('D04','How many race-result points did Ferrari score in 2022, excluding sprint points? Return only the total.',
 "SELECT SUM(r.points) FROM results r JOIN constructors c USING(constructorId) JOIN races ra USING(raceId) WHERE c.name='Ferrari' AND ra.year=2022",'results constructors races','aggregation'),
case('D05','For the 2023 British Grand Prix qualifying, return surnames and positions for the top three, ordered by position.',
 "SELECT d.surname,q.position FROM qualifying q JOIN drivers d USING(driverId) JOIN races r USING(raceId) WHERE r.year=2023 AND r.name='British Grand Prix' AND q.position<=3 ORDER BY q.position",'qualifying drivers races','join',True),
case('D06','What is the average recorded pit-stop duration in milliseconds for 2022? Return only the unrounded average.',
 'SELECT AVG(p.milliseconds) FROM pit_stops p JOIN races r USING(raceId) WHERE r.year=2022','pit_stops races','numeric'),
case('D07','What is the fastest recorded lap in milliseconds at the 2021 Abu Dhabi Grand Prix? Return only the minimum.',
 "SELECT MIN(l.milliseconds) FROM lap_times l JOIN races r USING(raceId) WHERE r.year=2021 AND r.name='Abu Dhabi Grand Prix'",'lap_times races','numeric'),
case('D08','How many distinct sprint races have results recorded for 2022? Return only the count.',
 'SELECT COUNT(DISTINCT s.raceId) FROM sprint_results s JOIN races r USING(raceId) WHERE r.year=2022','sprint_results races','distinct'),
case('D09','Return the names of the first five British constructors in alphabetical order.',
 "SELECT name FROM constructors WHERE nationality='British' ORDER BY name LIMIT 5",'constructors','filter',True),
case('D10','List circuit names whose country is exactly Moon, sorted alphabetically. An empty result is valid.',
 "SELECT name FROM circuits WHERE country='Moon' ORDER BY name",'circuits','empty',True),
case('D11','Return names and dates of the first five races in 2020, in round order.',
 'SELECT name,date FROM races WHERE year=2020 ORDER BY round LIMIT 5','races','ordering',True),
case('D12','How many races did Max Verstappen win in 2023? Return only the count.',
 "SELECT COUNT(*) FROM results r JOIN drivers d USING(driverId) JOIN races ra USING(raceId) WHERE d.forename='Max' AND d.surname='Verstappen' AND r.position='1' AND ra.year=2023",'results drivers races','join'),
case('D13','How many circuits are listed in Germany? Return only the count.',
 "SELECT COUNT(*) FROM circuits WHERE country='Germany'",'circuits','count'),
case('D14','What is the average latitude of circuits in Italy? Return only the unrounded value.',
 "SELECT AVG(lat) FROM circuits WHERE country='Italy'",'circuits','numeric'),
case('D15','What is the minimum latitude of circuits in Brazil? Return only the value.',
 "SELECT MIN(lat) FROM circuits WHERE country='Brazil'",'circuits','negative'),
case('D16','Return the 2022 drivers champion surname and points from the final race standings.',
 'SELECT d.surname,s.points FROM driver_standings s JOIN drivers d USING(driverId) JOIN races r USING(raceId) WHERE r.year=2022 AND s.position=1 ORDER BY r.round DESC LIMIT 1','driver_standings drivers races','standings'),
case('D17','Return the 2022 constructors champion name and points from the final race standings.',
 'SELECT c.name,s.points FROM constructor_standings s JOIN constructors c USING(constructorId) JOIN races r USING(raceId) WHERE r.year=2022 AND s.position=1 ORDER BY r.round DESC LIMIT 1','constructor_standings constructors races','standings'),
case('D18','Return driver surnames and grid positions for the top five starters at the 2023 Monaco Grand Prix, in grid order.',
 "SELECT d.surname,r.grid FROM results r JOIN drivers d USING(driverId) JOIN races ra USING(raceId) WHERE ra.year=2023 AND ra.name='Monaco Grand Prix' AND r.grid BETWEEN 1 AND 5 ORDER BY r.grid",'results drivers races','join',True),
case('D19','How many 2023 race results have the status exactly Engine? Return only the count.',
 "SELECT COUNT(*) FROM results r JOIN races ra USING(raceId) JOIN status s USING(statusId) WHERE ra.year=2023 AND s.status='Engine'",'results races status','status'),
case('D20','Return constructor names and constructor_results points for the 2023 Australian Grand Prix, ordered by points descending then name ascending.',
 "SELECT c.name,r.points FROM constructor_results r JOIN constructors c USING(constructorId) JOIN races ra USING(raceId) WHERE ra.year=2023 AND ra.name='Australian Grand Prix' ORDER BY r.points DESC,c.name",'constructor_results constructors races','join',True),

case('E01','How many races were held in 2019? Return only the count.',
 'SELECT COUNT(*) FROM races WHERE year=2019','races','count'),
case('E02','List circuit names in France alphabetically.',
 "SELECT name FROM circuits WHERE country='France' ORDER BY name",'circuits','filter',True),
case('E03','Return Sebastian Vettel\'s career race-win count only.',
 "SELECT COUNT(*) FROM results r JOIN drivers d USING(driverId) WHERE r.position='1' AND d.forename='Sebastian' AND d.surname='Vettel'",'results drivers','aggregation'),
case('E04','Return the top three constructor names and career race-win counts, ordered by wins descending then name ascending. Count race results only.',
 "SELECT c.name,COUNT(*) n FROM results r JOIN constructors c USING(constructorId) WHERE r.position='1' GROUP BY c.constructorId,c.name ORDER BY n DESC,c.name LIMIT 3",'results constructors','aggregation',True),
case('E05','Return names and rounds of all races in 2018, in round order.',
 'SELECT name,round FROM races WHERE year=2018 ORDER BY round','races','ordering',True),
case('E06','Return the driver surname and finishing position of the winner of the 2020 Italian Grand Prix.',
 "SELECT d.surname,r.position FROM results r JOIN drivers d USING(driverId) JOIN races ra USING(raceId) WHERE ra.year=2020 AND ra.name='Italian Grand Prix' AND r.position='1'",'results drivers races','join'),
case('E07','Return the minimum recorded pit-stop duration in milliseconds at the 2023 Bahrain Grand Prix.',
 "SELECT MIN(p.milliseconds) FROM pit_stops p JOIN races r USING(raceId) WHERE r.year=2023 AND r.name='Bahrain Grand Prix'",'pit_stops races','numeric'),
case('E08','Return the number of recorded lap-time rows at the 2022 Japanese Grand Prix.',
 "SELECT COUNT(*) FROM lap_times l JOIN races r USING(raceId) WHERE r.year=2022 AND r.name='Japanese Grand Prix'",'lap_times races','count'),
case('E09','Return driver surnames and sprint finishing positions for the top three at the 2023 Austrian Grand Prix, in position order.',
 "SELECT d.surname,s.position FROM sprint_results s JOIN drivers d USING(driverId) JOIN races r USING(raceId) WHERE r.year=2023 AND r.name='Austrian Grand Prix' AND s.position<=3 ORDER BY s.position",'sprint_results drivers races','sprint',True),
case('E10','Return the driver surname and qualifying position of the pole sitter at the 2022 Singapore Grand Prix.',
 "SELECT d.surname,q.position FROM qualifying q JOIN drivers d USING(driverId) JOIN races r USING(raceId) WHERE r.year=2022 AND r.name='Singapore Grand Prix' AND q.position=1",'qualifying drivers races','qualifying'),
case('E11','Return the 2016 drivers champion surname and points from final-race standings.',
 'SELECT d.surname,s.points FROM driver_standings s JOIN drivers d USING(driverId) JOIN races r USING(raceId) WHERE r.year=2016 AND s.position=1 ORDER BY r.round DESC LIMIT 1','driver_standings drivers races','standings'),
case('E12','Return the 2017 constructors champion name and points from final-race standings.',
 'SELECT c.name,s.points FROM constructor_standings s JOIN constructors c USING(constructorId) JOIN races r USING(raceId) WHERE r.year=2017 AND s.position=1 ORDER BY r.round DESC LIMIT 1','constructor_standings constructors races','standings'),
case('E13','Return the names of the first five Italian constructors alphabetically.',
 "SELECT name FROM constructors WHERE nationality='Italian' ORDER BY name LIMIT 5",'constructors','filter',True),
case('E14','Return the surnames and dates of birth of the first five Japanese drivers alphabetically by surname then forename.',
 "SELECT surname,dob FROM drivers WHERE nationality='Japanese' ORDER BY surname,forename LIMIT 5",'drivers','filter',True),
case('E15','Return circuit names and locations in Japan alphabetically by circuit name.',
 "SELECT name,location FROM circuits WHERE country='Japan' ORDER BY name",'circuits','filter',True),
case('E16','Return the count of circuits whose country is exactly Atlantis.',
 "SELECT COUNT(*) FROM circuits WHERE country='Atlantis'",'circuits','zero'),
case('E17','List race names in year 1800 alphabetically. An empty result is valid.',
 'SELECT name FROM races WHERE year=1800 ORDER BY name','races','empty',True),
case('E18','Return the earliest and latest season years, in that column order.',
 'SELECT MIN(year),MAX(year) FROM seasons','seasons','range'),
case('E19','Return the minimum and maximum recorded race years, in that column order.',
 'SELECT MIN(year),MAX(year) FROM races','races','range'),
case('E20','Return the number of distinct race-winning drivers in 2009.',
 "SELECT COUNT(DISTINCT r.driverId) FROM results r JOIN races ra USING(raceId) WHERE ra.year=2009 AND r.position='1'",'results races','distinct'),
case('E21','Return constructor names and race-result points totals in 2014, excluding sprints, for the top three by points descending then name ascending.',
 'SELECT c.name,SUM(r.points) p FROM results r JOIN constructors c USING(constructorId) JOIN races ra USING(raceId) WHERE ra.year=2014 GROUP BY c.constructorId,c.name ORDER BY p DESC,c.name LIMIT 3','results constructors races','aggregation',True),
case('E22','Return driver surnames and counts of race podiums in 2010, for the top three by podium count descending then surname ascending.',
 "SELECT d.surname,COUNT(*) n FROM results r JOIN drivers d USING(driverId) JOIN races ra USING(raceId) WHERE ra.year=2010 AND r.position IN ('1','2','3') GROUP BY d.driverId,d.surname ORDER BY n DESC,d.surname LIMIT 3",'results drivers races','aggregation',True),
case('E23','Return the count of race results with status exactly Collision during 2015.',
 "SELECT COUNT(*) FROM results r JOIN races ra USING(raceId) JOIN status s USING(statusId) WHERE ra.year=2015 AND s.status='Collision'",'results races status','status'),
case('E24','Return status text and occurrence counts for the three most frequent result statuses in 2018, ordered by count descending then status text ascending.',
 'SELECT s.status,COUNT(*) n FROM results r JOIN status s USING(statusId) JOIN races ra USING(raceId) WHERE ra.year=2018 GROUP BY s.statusId,s.status ORDER BY n DESC,s.status LIMIT 3','results status races','aggregation',True),
case('E25','Return the count of recorded pit stops at the 2021 Hungarian Grand Prix.',
 "SELECT COUNT(*) FROM pit_stops p JOIN races r USING(raceId) WHERE r.year=2021 AND r.name='Hungarian Grand Prix'",'pit_stops races','count'),
case('E26','Return the unrounded average recorded lap time in milliseconds at the 2019 Spanish Grand Prix.',
 "SELECT AVG(l.milliseconds) FROM lap_times l JOIN races r USING(raceId) WHERE r.year=2019 AND r.name='Spanish Grand Prix'",'lap_times races','numeric'),
case('E27','Return the count of distinct races with sprint results in 2021.',
 'SELECT COUNT(DISTINCT s.raceId) FROM sprint_results s JOIN races r USING(raceId) WHERE r.year=2021','sprint_results races','distinct'),
case('E28','Return the driver surname and Q3 time of the pole sitter at the 2019 Canadian Grand Prix.',
 "SELECT d.surname,q.q3 FROM qualifying q JOIN drivers d USING(driverId) JOIN races r USING(raceId) WHERE r.year=2019 AND r.name='Canadian Grand Prix' AND q.position=1",'qualifying drivers races','qualifying'),
case('E29','Return constructor names and constructor_results points at the 2020 Portuguese Grand Prix, ordered by points descending then name ascending.',
 "SELECT c.name,cr.points FROM constructor_results cr JOIN constructors c USING(constructorId) JOIN races r USING(raceId) WHERE r.year=2020 AND r.name='Portuguese Grand Prix' ORDER BY cr.points DESC,c.name",'constructor_results constructors races','join',True),
case('E30','Return the circuit name and country hosting the 2021 Turkish Grand Prix.',
 "SELECT c.name,c.country FROM races r JOIN circuits c USING(circuitId) WHERE r.year=2021 AND r.name='Turkish Grand Prix'",'races circuits','join'),
case('E31','Return the maximum latitude among circuits in Australia.',
 "SELECT MAX(lat) FROM circuits WHERE country='Australia'",'circuits','negative'),
case('E32','Return the total recorded race laps completed by Fernando Alonso during 2023.',
 "SELECT SUM(r.laps) FROM results r JOIN drivers d USING(driverId) JOIN races ra USING(raceId) WHERE d.forename='Fernando' AND d.surname='Alonso' AND ra.year=2023",'results drivers races','aggregation'),
case('E33','Return Sergio Perez\'s race-result points total during 2021, excluding sprints.',
 "SELECT SUM(r.points) FROM results r JOIN drivers d USING(driverId) JOIN races ra USING(raceId) WHERE d.driverRef='perez' AND ra.year=2021",'results drivers races','aggregation'),
case('E34','Return the number of races held at Silverstone during 2020.',
 "SELECT COUNT(*) FROM races r JOIN circuits c USING(circuitId) WHERE c.circuitRef='silverstone' AND r.year=2020",'races circuits','alias'),
case('E35','Return the name and date of the earliest recorded race, ordered by date then raceId, limited to one.',
 'SELECT name,date FROM races ORDER BY date,raceId LIMIT 1','races','ordering',True),
case('E36','Return the count of distinct constructors appearing in 2023 race results.',
 'SELECT COUNT(DISTINCT r.constructorId) FROM results r JOIN races ra USING(raceId) WHERE ra.year=2023','results races','distinct'),
case('E37','Return the number of recorded driver rows with British nationality.',
 "SELECT COUNT(*) FROM drivers WHERE nationality='British'",'drivers','count'),
case('E38','Return the count of qualifying records with a non-null, nonempty Q3 time at the 2023 Belgian Grand Prix.',
 "SELECT COUNT(*) FROM qualifying q JOIN races r USING(raceId) WHERE r.year=2023 AND r.name='Belgian Grand Prix' AND q.q3 IS NOT NULL AND q.q3<>''",'qualifying races','null'),
case('E39','Return names and countries of circuits hosting 2023 races, with duplicates removed, sorted by circuit name.',
 'SELECT DISTINCT c.name,c.country FROM races r JOIN circuits c USING(circuitId) WHERE r.year=2023 ORDER BY c.name','races circuits','distinct',True),
case('E40','Return the driver surnames and final standings positions of the top five in 2013, ordered by position.',
 'SELECT d.surname,s.position FROM driver_standings s JOIN drivers d USING(driverId) JOIN races r USING(raceId) WHERE r.year=2013 AND r.round=(SELECT MAX(round) FROM races WHERE year=2013) AND s.position<=5 ORDER BY s.position','driver_standings drivers races','subquery',True),
]
